ROOT_MAPPINGS = {
    "running": "چلول",
    "studies": "زده کړه",
    "studied": "زده کړه",
    "studying": "زده کړه",
    "happier": "خوښ",
    "happiness": "خوښي",
    "achievable": "ترلاسه کېدونکی",
    "agreement": "تړون",
    "agreements": "تړون",
    "national": "ملي",
    "nationality": "تابعيت",
    "analysis": "تحليل",
    "analyzed": "تحليل",
    "analyzing": "تحليل",
    "powerful": "زورور",
    "powerless": "بې وسه",
    "players": "لوبغاړي",
    "playing": "لوبه",
    "played": "لوبه",
    "dances": "نڅا",
    "dancing": "نڅا",
    "danced": "نڅا",
    "walkers": "پلي",
    "walking": "تګ",
    "walked": "تګ",
    "easily": "په آسانۍ",
    "easier": "آسان",
    "easiest": "تر ټولو آسان",
    "kindness": "مهرباني",
    "kindly": "په مهربانۍ",
    "books": "کتابونه",
    "writers": "ليکوالان",
    "writing": "ليکل",
    "wrote": "وليکل",
    "driven": "چلول شوی",
    "driving": "چلول",
    "drives": "چلول",
    "tries": "هڅه",
    "trying": "هڅه",
    "tried": "هڅه وکړه",
    "flies": "الوتنې",
    "flying": "الوتنه",
    "bought": "رانيول",
    "shopping": "پېرودنه",
    "shoppers": "پېرودونکي",
    "readable": "د لوست وړ",
    "readability": "لوستنې وړتیا",
    "instructions": "لارښوونې",
    "instruction": "لارښوونه",
    "instructing": "لارښوونه کول",
    "productivity": "توليد",
    "productive": "توليدوونکی",
    "dangerously": "په خطرناک ډول",
    "danger": "خطر",
    "teachers": "ښوونکي",
    "teaching": "تدریس",
    "taught": "تدریس شو",
    "cities": "ښارونه",
    "families": "کورنۍ",
    "functional": "فعاله",
    "functions": "دندې",
    "functionalism": "فعاليت پالنه",
    "performing": "اجرا",
    "performance": "اجراات",
    "transform": "بدلول",
    "transformation": "بدلون",
    "consider": "غور کول",
    "considering": "غور",
    "considered": "غور شوی",
    "motivates": "تشویقول",
    "motivated": "تشویق شوی",
    "motivating": "تشویق",
    "democracy": "ډيموکراسي",
    "democratic": "ډيموکراتيک",
    "democrats": "ډيموکراتان",
}